/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;

/**
 *
 * @author Asus
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class ApplyPage extends javax.swing.JFrame {

    /**
     * Creates new form ApplyPage
     */
    public static int pgst,pbuet,pmedical,pengineering,pdu,pagri,pju,pcu,pdental,total;
    static{
        pgst = pbuet = pmedical = pengineering = pdu = pagri = pju = pcu = pdental =  0;
        total = 1;
    }
    
    public ApplyPage() {
        initComponents();
        myfunc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SectionGrp = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextname = new javax.swing.JTextField();
        jname = new javax.swing.JLabel();
        jFname = new javax.swing.JLabel();
        jTextFname = new javax.swing.JTextField();
        jMname = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jreg = new javax.swing.JLabel();
        jroll = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        jTextreg = new javax.swing.JTextField();
        jTextroll = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jCheckBoxScience = new javax.swing.JCheckBox();
        jCheckBoxCommerce = new javax.swing.JCheckBox();
        jCheckBoxArts = new javax.swing.JCheckBox();
        jCheckBoxGst = new javax.swing.JCheckBox();
        jCheckBoxEng = new javax.swing.JCheckBox();
        jCheckBoxBuet = new javax.swing.JCheckBox();
        jCheckBoxDu = new javax.swing.JCheckBox();
        jCheckBoxMedical = new javax.swing.JCheckBox();
        jCheckBoxArgi = new javax.swing.JCheckBox();
        jCheckBoxDental = new javax.swing.JCheckBox();
        jCheckBoxJu = new javax.swing.JCheckBox();
        jCheckBoxCu = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jamount = new javax.swing.JLabel();
        jTextamount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 0, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 100, 84));
        jLabel1.setText(" APPLICATION");
        jLabel1.setAlignmentX(15.0F);

        jTextname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextname.setForeground(new java.awt.Color(71, 198, 56));

        jname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jname.setForeground(new java.awt.Color(51, 51, 255));
        jname.setText("Name");

        jFname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jFname.setForeground(new java.awt.Color(51, 51, 255));
        jFname.setText("Father's Name");

        jTextFname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextFname.setForeground(new java.awt.Color(71, 198, 56));
        jTextFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFnameActionPerformed(evt);
            }
        });

        jMname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMname.setForeground(new java.awt.Color(51, 51, 255));
        jMname.setText("Mother's Name");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(71, 198, 56));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Date of Birth");

        jreg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jreg.setForeground(new java.awt.Color(51, 51, 255));
        jreg.setText("REGIRSTRATION NO.");

        jroll.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jroll.setForeground(new java.awt.Color(51, 51, 255));
        jroll.setText("ROLL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("ADDRESS");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("MOBILE NO.");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("GENDER");

        SectionGrp.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox1.setText("MALE");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SectionGrp.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox2.setText("FEMALE");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(71, 198, 56));
        jTextField4.setText("01");

        jTextreg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextreg.setForeground(new java.awt.Color(71, 198, 56));

        jTextroll.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextroll.setForeground(new java.awt.Color(71, 198, 56));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(71, 198, 56));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("EMAIL");

        jTextField8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(71, 198, 56));

        submitButton.setBackground(new java.awt.Color(51, 255, 102));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 102, 0));
        submitButton.setText("SUBMIT");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        SectionGrp.add(jCheckBoxScience);
        jCheckBoxScience.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxScience.setForeground(new java.awt.Color(187, 23, 12));
        jCheckBoxScience.setText("Science");
        jCheckBoxScience.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SectionGrp.add(jCheckBoxCommerce);
        jCheckBoxCommerce.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxCommerce.setForeground(new java.awt.Color(0, 149, 80));
        jCheckBoxCommerce.setText("Commerce");
        jCheckBoxCommerce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SectionGrp.add(jCheckBoxArts);
        jCheckBoxArts.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxArts.setForeground(new java.awt.Color(186, 208, 0));
        jCheckBoxArts.setText("Arts");
        jCheckBoxArts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxGst.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxGst.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxGst.setText("GST");
        jCheckBoxGst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxGst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGstActionPerformed(evt);
            }
        });

        jCheckBoxEng.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxEng.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxEng.setText("ENGINEERING");
        jCheckBoxEng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEngActionPerformed(evt);
            }
        });

        jCheckBoxBuet.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxBuet.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxBuet.setText("BUET");
        jCheckBoxBuet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxDu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxDu.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxDu.setText("DU");
        jCheckBoxDu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDuActionPerformed(evt);
            }
        });

        jCheckBoxMedical.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxMedical.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxMedical.setText("MEDICAL");
        jCheckBoxMedical.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxArgi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxArgi.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxArgi.setText("AGRICULTURE");
        jCheckBoxArgi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxDental.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxDental.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxDental.setText("DENTAL");
        jCheckBoxDental.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxJu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxJu.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxJu.setText("JU");
        jCheckBoxJu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxCu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxCu.setForeground(new java.awt.Color(255, 101, 154));
        jCheckBoxCu.setText("CU");
        jCheckBoxCu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1040635620000L), new java.util.Date(670066020000L), new java.util.Date(1272014820000L), java.util.Calendar.MONTH));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jamount.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jamount.setForeground(new java.awt.Color(30, 208, 99));
        jamount.setText("Amount of Pay");

        jTextamount.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jTextamount.setForeground(new java.awt.Color(252, 17, 23));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 208, 99));
        jLabel13.setText("TK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFname, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jMname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreg, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jroll, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextname)
                    .addComponent(jTextFname)
                    .addComponent(jTextField3)
                    .addComponent(jTextreg)
                    .addComponent(jTextField4)
                    .addComponent(jTextroll)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxScience)
                            .addComponent(jCheckBoxCommerce)
                            .addComponent(jCheckBoxArts))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxGst)
                                .addGap(33, 33, 33)
                                .addComponent(jCheckBoxEng)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxBuet)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxDu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextamount, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jCheckBoxMedical)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBoxArgi))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jCheckBoxJu)
                                            .addGap(45, 45, 45)
                                            .addComponent(jCheckBoxCu)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBoxDental))))
                        .addContainerGap(73, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxScience)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCommerce))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxArts))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxGst)
                            .addComponent(jCheckBoxEng)
                            .addComponent(jCheckBoxBuet)
                            .addComponent(jCheckBoxDu)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jreg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxMedical)
                    .addComponent(jCheckBoxArgi)
                    .addComponent(jCheckBoxDental))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jroll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxJu)
                            .addComponent(jCheckBoxCu))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        JOptionPane.showMessageDialog(this,"Successfully Submitted!");
        
            try {
            // TODO add your handling code here:
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://127.0.0.1:3306/student_info?serverTimezone=UTC";
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement statement = conn.createStatement();
            String name = jTextname.getText();
            String sreg = jTextreg.getText();
            String sroll = jTextroll.getText();
            String samount = jTextamount.getText();
            String grp ="";
           
           // jTextFname.setText(name);
            if(jCheckBoxScience.isSelected())
            {
                grp = "scinece";
            }
            else if(jCheckBoxCommerce.isSelected())
            {
                grp = "commerce";
            }
            else if(jCheckBoxArts.isSelected())
            {
                grp = "arts";
            }
            int roll = Integer.parseInt(sroll);
            int reg = Integer.parseInt(sreg);
            int amount = Integer.parseInt(samount);
            int agri,buet,gst,du,medical,dental,ju,cu,engineering;
            agri = buet = gst = du = medical = dental = ju = cu = engineering = 0;
            
            if(jCheckBoxArgi.isSelected())
            {
                agri = 1;
                pagri++;
                total++;
            }
            if(jCheckBoxBuet.isSelected())
            {
                buet = 1;
                pbuet++;
                total++;
            }
            if(jCheckBoxCu.isSelected())
            {
                cu = 1;
                pcu++;
                total++;
            }
            if(jCheckBoxDental.isSelected())
            {
                dental = 1;
                pdental++;
                total++;
            }
            if(jCheckBoxDu.isSelected())
            {
                du = 1;
                pdu++;
                total++;
            }
            if(jCheckBoxEng.isSelected())
            {
                engineering = 1;
                pengineering++;
                total++;
            }
            if(jCheckBoxGst.isSelected())
            {
                gst = 1;
                pgst++;
                total++;
            }
            if(jCheckBoxJu.isSelected())
            {
                ju = 1;
                pju++;
                total++;
                
            }
            if(jCheckBoxMedical.isSelected())
            {
                medical = 1;
                pmedical++;
                total++;
            }
            
            String query = "INSERT INTO apply_info (name, reg, roll, grp, gst, buet, engineering, du, medical, ju, cu, dental, agriculture, amount) VALUES ('"+name+"',"+reg+","+roll+",'"+grp+"',"+gst+","+buet+","+engineering+","+du+","+medical+","+ju+","+cu+","+dental+","+agri+","+amount+")";
            System.out.print(query);
            statement.executeUpdate(query);
           
            statement.close();
            conn.close();
            
            
        } catch (ClassNotFoundException | SQLException ex) {
           Logger.getLogger(TestWindowsClass.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         try {
            // TODO add your handling code here:
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://127.0.0.1:3306/progreess_info?serverTimezone=UTC";
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement statement = conn.createStatement();
            
            String query = "SELECT  `number` FROM `progress` WHERE name = \"gst\" ";
                    
            /** Incomplete section 
             * query get value then update that value
            *
            *
            */
            ResultSet result = statement.executeQuery(query);
            String sid = result.getString("number");
            int id = Integer.parseInt(sid);
            System.out.println(id);
            jTextFname.setText(sid);
         }
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TestWindowsClass.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         String s = jTextname.getText();
       //  jTextField8.setText(s);
         System.out.println(s);
            
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jCheckBoxGstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGstActionPerformed

    private void jCheckBoxEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEngActionPerformed

    private void jCheckBoxDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDuActionPerformed

    private void jTextFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyPage().setVisible(true);
            }
        });
    }
    
    private void myfunc()
    {
       // setBounds(0,0,1000,800);
        setSize(1100,800);
        setLocationRelativeTo(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SectionGrp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBoxArgi;
    private javax.swing.JCheckBox jCheckBoxArts;
    private javax.swing.JCheckBox jCheckBoxBuet;
    private javax.swing.JCheckBox jCheckBoxCommerce;
    private javax.swing.JCheckBox jCheckBoxCu;
    private javax.swing.JCheckBox jCheckBoxDental;
    private javax.swing.JCheckBox jCheckBoxDu;
    private javax.swing.JCheckBox jCheckBoxEng;
    private javax.swing.JCheckBox jCheckBoxGst;
    private javax.swing.JCheckBox jCheckBoxJu;
    private javax.swing.JCheckBox jCheckBoxMedical;
    private javax.swing.JCheckBox jCheckBoxScience;
    private javax.swing.JLabel jFname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFname;
    private javax.swing.JTextField jTextamount;
    private javax.swing.JTextField jTextname;
    private javax.swing.JTextField jTextreg;
    private javax.swing.JTextField jTextroll;
    private javax.swing.JLabel jamount;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jreg;
    private javax.swing.JLabel jroll;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
